# Generated by Django 4.0.3 on 2022-10-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_agent_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='house',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
